[tox]
envlist = packaging,test

[testenv:test]
deps =
	pytest
commands =
	pytest test

[testenv:packaging]
deps =
	check-manifest
	readme-renderer
commands =
	check-manifest
	python setup.py check -m -r -s
